type: error
get:
  is: [accessToken, jobschedulerController]
  queryParameters:
    taskId:
      required: true
      type: integer
      description: Task Id
      example: 4711
  description: |
    <h2><<description>></h2>
  responses:
    200:
      description: Content of task log for download
      headers:
        Content-Disposition:
          type: string
          required: true
          example: attachment;filename=xxx.task.log
      body:
        text/plain:
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <<tr><td>``controllerId``</td><td>required, string</td><td>Controller ID</td><td>myController</td><td></td></tr>
    <tr><td>``taskId``</td><td>required, integer</td><td>Task Id</td><td>4711</td><td></td></tr>
    </tbody></table>
  body:
    application/json:
      schema: taskFilter
      example: |
        {
          "controllerId": "myController",
          "taskId": 4711
        }
  responses:
    200:
      description: Content of task log for download
      headers:
        Content-Disposition:
          type: string
          required: true
          example: attachment;filename=xxx.task.log
        Content-Type:
          type: string
          required: true
          default: text/plain
      body:
        text/plain:
