type: error
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="16%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``controllerId``</td><td>required, string</td><td>Controller ID</td><td>myController</td><td></td></tr>
    <tr><td>``orderIds``</td><td>optional, array</td>
    <td>Specified the order ids which should be modified.<br/>
      If this parameter is specified then the parameters ``workflowIds``, ``folders`` and ``states`` where applicable are ignored.</td>
    <td> [
      <div style="padding-left:10px;">"daily"</div>
      ]</td>
    <td></td></tr>
    <tr><td>``workflowIds``</td><td>optional, array[object]</td>
    <td>Filtered response by a collection of workflows specified by its path and optional version<br/>
        If this parameter is specified the parameter ``folders`` where applicable are ignored.</td>
    <td> [{
        <div style="padding-left:10px;">"path": "/path/to/workflow",</div>
        <div style="padding-left:10px;">"versionId": "c79caab4-4e72-4818-bae7-902f1037d8b6"</div>
    }]</td>
    <td></td>
    </tr>
    <tr><td style="padding-left:20px;">``path``</td><td>required, string</td><td>Field for each item in ``workflowIds`` to specify the path of a workflow</td><td></td><td></td></tr>
    <tr><td style="padding-left:20px;">``version``</td><td>optional, string</td><td>Field for each in ``workflowIds`` to specify the version of a workflow</td><td></td><td></td></tr>
    <tr><td>``folders``</td><td>optional, array[object]</td><td>Limits the result to a collection of folders</td>
    <td> [{
        <div style="padding-left:10px;">"folder": "/sos",</div>
        <div style="padding-left:10px;">"recursive": true</div>
    }]</td>
    <td></td></tr>
    <tr><td>``states``</td><td>optional, array</td>
    <td>Filtered all orders with states such as
    <ul>
      <li>PENDING</li>
      <li>SCHEDULED</li>
      <li>INPROGRESS</li>
      <li>RUNNING</li>
      <li>SUSPENDED</li>
      <li>WAITING</li>
      <li>PROMPTING</li>
      <li>FAILED</li>
      <li>BLOCKED</li>
    </ul>
    </td><td>["SUSPENDED"]</td><td></td></tr>
    <<dateFromParam>>
    <<dateToParam>>
    <<timeZoneParam>>
    <<positionParam>>
    <<variablesParam>>
    <<cycleParam>>
    <<signalParam>>
    <<audit>>
    </tbody></table>

  body:
    application/json:
      schema: <<schema>>
      example: |
        {
          "controllerId": "myController",
          "orderIds": [
            "order1",
            "order2",
            "order3",
            "order4",
            "order5"
          ]
        }
  responses:
    200:
      description: It returns an _ok_. This reply code comes only for bulk operations if all commands were successful.
      body:
        application/json:
          schema: ok
          example: |
            {
              "deliveryDate":"2020-08-24T21:13:35Z",
              "surveyDate":"2020-08-24T21:13:34Z",
              "ok":true
            }
    419:
