type: error
get:
  is: [accessToken, jobschedulerController]
  queryParameters:
    historyId:
      required: true
      type: integer
      description: The history id of an order
      example: 4711
  description: |
    <h2><<description>></h2>
  responses:
    200:
      description: Content of order log for download
      headers:
        Content-Disposition:
          type: string
          required: true
          example: attachment;filename=xxx.order.log
        Content-Type:
          type: string
          required: true
          default: application/octet-stream
      body:
        application/octet-stream:
        text/plain:
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``controllerId``</td><td>required, string</td><td>JobScheduler Controller ID</td><td>scheduler</td><td></td></tr>
    <tr><td>``historyId``</td><td>required; integer</td><td>The history id of an order</td><td>4711</td><td></td></tr>
    </tbody></table>
  body:
    application/json:
      schema: orderHistoryFilter
      example: |
        {
            "controllerId":"scheduler",
            "historyId": 4711,
            "jobChain": "/test/foo/bar1",
            "orderId": "order1"
        }
  responses:
    200:
      description: Content of order log for download
      headers:
        Content-Disposition:
          type: string
          required: true
          example: attachment;filename=xxx.order.log
        Content-Type:
          type: string
          required: true
          default: text/plain
      body:
        text/plain:
