type: error
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="16%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``controllerId``</td><td>required, string</td><td>Controller ID</td><td>myController</td><td></td></tr>
    <tr><td>``calendarIds``</td><td>optional, array</td>
      <td>Filtered response by a collection of calendars specified by its calendar id. Parameter ``calendars`` is ignored if this parameter is defined.</td>
      <td> [
        <div style="padding-left:10px;">4711,</div>
        <div style="padding-left:10px;">4712</div>
      ]</td>
      <td></td>
    </tr>
    <tr><td>``calendars``</td><td>optional, array</td>
      <td>Filtered response by a collection of calendars specified by its calendar path.
      <td> [
        <div style="padding-left:10px;">"/sos/myCalendar",</div>
        <div style="padding-left:10px;">"/sos/myCalendar2"</div>
      ]</td>
       <td></td>
    </tr>
    <<audit>>
    </tbody></table>

  body:
    application/json:
      schema: modifyCalendars
      example: |
        {
          "calendars": [
            "/test/testCalendar",
            "/test/testCalendar",
            "/test/testCalendar2"
          ]
        }
  responses:
    200:
      description: It returns an _ok_. This reply code comes only for bulk operations if all commands were successful.
      body:
        application/json:
          schema: ok
          example: |
            {
              "deliveryDate":"2016-05-05T21:13:35Z",
              "ok":true
            }
    419:
