queryParameters:
  accessToken:
    type: string
    description: |
       is required if the header doesn't contain ``X-Access-Token``
    required: false
    example: 550e8400-e29b-11d4-a716-446655440000
