queryParameters:
  accessToken:
    type: string
    description: |
       is used if the header doesn't contain ``X-Access-Token``
       necessary if this url is called with _window.open_ or _window.location.href_ etc.
    required: false
    example: 550e8400-e29b-11d4-a716-446655440000
