queryParameters:
  filename:
      required: false
      type: string
      description: |
        Name of a file from e.g. ../log/info<br/>This file will be returned if exists
      example: sos-download-5961566003164029224.tmp