queryParameters:
  objectType:
    type: string
    description: |
      Type of a Controller object. Possible values are 
      <ul><li>"WORKFLOW"</li>
        <li>"JOBRESOURCE"</li>
        <li>"LOCK"</li>
        <li>"NOTICEBOARD"</li>
        <li>"FILEORDERSOURCE"</li>
        <li>"WORKINGDAYSCALENDAR"</li>
        <li>"NONWORKINGDAYSCALENDAR"</li>
        <li>"INCLUDESCRIPT"</li>
        <li>"SCHEDULE"</li>
        <li>"JOB"</li>
      </ul>
    required: true
  jobName:
    type: string
    description: |
      If the ``objectType`` is a JOB then the Workflow path is expected in ``path`` and the job name here.
    required: false
