type: error
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <<description1>>
    <<description2>>
    <<description3>>
    <<description4>>
    <<description5>>
    <<audit>>
    </tbody></table>
  body:
    application/json:
      schema: <<schema>>
      example: <<example>>
  responses:
    200:
      description: |
        **Confirm <span style="text-transform: capitalize;"><<resourcePathName>></span> successfully**
      body:
        application/json:
          example: |
            {
              "deliveryDate":"2020-05-05T21:13:35Z",
              "ok":true
            }
          schema: ok
