type: error
post:
  description: |
    <h2>Register Controller objects for collecting events</h2>
    <p>Events can be sent for multiple Controller.
    The request remains open until a requested event has been received or a timeout of ~6min is reached.
    Only one ./event request should be active per browser tab.
    </p>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``controllers``</td><td>required, array</td>
    <td>This collection contains a required ``controllerId`` and its objects of interest<br/>
    The first item of the collection has to be the current controllerId.</td>
    <td> [{
      <div style="padding-left:10px;">"controllerId":"scheduler",</div>
      <div style="padding-left:10px;">"eventId":1480088631000000,</div>
      <!-- div style="padding-left:10px;">"objects":[{...objects...}]</div -->
      }]</td><td></td></tr>
    <tr><td style="padding-left:20px;">``eventId``</td><td>optional, string</td>
    <td>Every response contains for each Controller a new eventId for the next call.<br/>
    If the eventId is empty then the web service calculates the eventId.</td>
    <td>"eventId":"1480088631000000"</td><td>Milliseconds of current timestamp * 1000</td></tr>
    </tbody></table>
  body:
    application/json:
      schema: <<schema>>
      example: <<example>>
  responses:
    200:
      description: <<description200>>
      body:
        application/json:
          example: <<example200>>
          schema: <<schema200>>
    434:
