type: error
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``controllerId``</td><td>optional, string</td><td>Controller ID</td><td>myController</td><td></td></tr>
    </tbody></table>
  body:
    application/json:
      schema: jsFilter
      example: |
        {
          "controllerId":"scheduler"
        }
  responses:
    200:
      description: <<description200>>
      body:
        application/json:
          example: <<example200>>
          schema: <<schema200>>
