type: error
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>No parameters in the POST body</h4>

  body?:
    application/json:
  responses:
    200:
      description: <<description200>>
      body:
        application/json:
          schema: <<schema200>>
          example: <<example200>>
    420:
      body:
        application/json:
    440:
      body:
        application/json:
