type: error
post:
  description: |
    <h2>Collects events</h2>
    <p>The request remains open until a requested event has been received or a timeout of ~3min is reached.
    Only one ./event request should be active per browser tab.
    </p>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``controllerId``</td><td>required, string</td><td>Controller ID</td><td>myController</td><td></td></tr>
    <tr><td>``eventId``</td><td>optional, string</td>
    <td>The response contains a new eventId for the next call.<br/>
    If the eventId is empty then the web service calculates the eventId.</td>
    <td>"eventId":"1612225325"</td><td>Seconds of current timestamp</td></tr>
    </tbody></table>
  body:
    application/json:
      schema: <<schema>>
      example: |
          {
            "controllerId":"myController",
            "eventId":1613396090
          }
  responses:
    200:
      description: <<description200>>
      body:
        application/json:
          example: <<example200>>
          schema: <<schema200>>
    434:
