type: error
post:
  description: |
    <h2>Log</h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``controllerId``</td><td>required, string</td><td>Controller ID</td><td>myController</td><td></td></tr>
    <<description1>>
    <<description2>>
    <<description3>>
    </tbody></table>

  body:
    application/json:
      schema: <<schema>>
      example: <<example>>
  responses:
    200:
      headers:
        X-Log-Complete:
          type: boolean
          required: true
        X-Log-Event-Id:
          type: number
          required: false
        X-Log-Task-Id:
          description: for ./task/log
          type: number
          required: false
      body:
        text/plain:
          example: <<example200>>
    420:
      body:
        application/json:
    440:
      body:
        application/json:
