type: error
post:
  description: |
    <h2><<description>></h2>
    ___
    <h4>Parameters in the POST body schema</h4>
    <table class="params" style="table-layout:auto;">
    <colgroup>
      <col width="10%"/>
      <col width="10%"/>
      <col width="*"/>
      <col width="20%"/>
      <col width="10%"/>
    </colgroup>
    <thead>
    <tr><th>Name</th><th>Type</th><th>Description</th><th>Example</th><th>Default</th>
    </thead><tbody>
    <tr><td>``controllerId``</td><td>optional, string</td><td>Controller ID (can be empty if and only if a new Controller (Cluster) will be registered)</td><td>scheduler</td><td></td></tr>
    <tr><td>``controllers``</td><td>required, array</td><td>Controllers of a cluster or one standalone Controller
    <br/>each Controller has the following fields</td><td></td><td></td></tr>
    <tr><td style="padding-left:20px;">``url``</td><td>required, string</td><td>URL of the Controller instance</td><td></td><td></td></tr>
    <tr><td style="padding-left:20px;">``clusterUrl``</td><td>optional, string</td><td>Only for a Cluster: A URL that the Controller instances use to connect to each other</td><td></td><td>``url``</td></tr>
    <tr><td style="padding-left:20px;">``role``</td><td>required, string</td><td>Role (STANDALONE, PRIMARY or BACKUP) of the Controller</td><td></td><td></td></tr>
    <tr><td style="padding-left:20px;">``title``</td><td>optional, string</td><td>A title that is used when displaying the Controller in JOC Cockpit</td><td></td><td></td></tr>
    <<audit>>
    </tbody></table>
  body:
    application/json:
      schema: jsRegister
      example: |
        {
           "controllers": [{
               "url": "https://controller-2-0-primary:4443",
               "title": "PRIMARY",
               "role": "PRIMARY",
               "clusterUrl": "https://controller-2-0-primary:4443"
            },
            {
               "url": "https://controller-2-0-secondary:4443",
               "role": "BACKUP",
               "clusterUrl": "https://controller-2-0-secondary:4443",
               "title": "SECONDARY"
            }],
            "controllerId": "testsuite"
        }
  responses:
    200:
      description: |
        **Confirm <span style="text-transform: capitalize;"><<resourcePathName>></span> successfully**
      body:
        application/json:
          example: |
            {
              "deliveryDate":"2016-05-05T21:13:35Z",
              "ok":true
            }
          schema: ok
