post:
  description: |
    <h2>Authenticates account and starts session</h2>
  headers:
    Authorization:
      description: String consisting of "Basic " and the base64 encoded "user:password". This applies to user/password authentication only.
      type: string
      example: Basic cm9vdpzZWNNyZXQ=
  responses:
    200:
      description: Get access token
      headers:
        X-Access-Token:
          type: string
          required: true
          example: 550e8400-e29b-11d4-a716-446655440000
      body:
        application/json:
          schema: security
          example: |
            {
              "user": "root",
              "accessToken": "550e8400-e29b-11d4-a716-446655440000",
              "role": "all",
              "isAuthenticated": true,
              "isPermitted": false,
              "sessionTimeout": 1800,
              "enableTouch": true
            }
    401:
      description: Unauthorized!
      body:
        application/json:
          schema: security
          example: |
            {
              "user": "root",
              "message": "User or password are invalid",
              "isAuthenticated": false,
              "isPermitted": false
            }
